-- Seed sample data for MediTracker: roles, users, medicines
-- Run:
--   docker exec -i meditracker-db psql -U myuser -d meditracker < /docker-entrypoint-initdb.d/seed-sample.sql
-- Or on Windows:
--   docker exec -i meditracker-db psql -U myuser -d meditracker < C:\dev\projects\MediTracker\deploy\db-backup\seed-sample.sql

BEGIN;

-- 1) Roles
INSERT INTO role (role_id, role_name, description)
VALUES
    (1, 'ADMIN', 'Administrator role with full permissions'),
    (2, 'DOCTOR', 'Doctor role to manage patient prescriptions'),
    (3, 'PATIENT', 'Patient role to manage their own prescriptions')
ON CONFLICT (role_id) DO NOTHING;

-- 2) Users
-- Password stored as BCrypt hash (for 'passwod')
-- Hash generated by BCrypt (work factor 10) example:
-- $2a$10$LhWf7CkS3qYvEw2dQeEBeuS2QeYQf2i2RzXwGvYhC5vGZBqvT1t9y
-- Replace below with a known working hash if your encoder expects a specific version ($2a vs $2b)

INSERT INTO users (user_id, name, username, email, password, created_at, updated_at)
VALUES (
    1,
    'Admin User',
    'admin',
    'Hewo7536@gmail.com',
    '$2a$10$C0/0w3b6yUUI9uJt1b0W6./pA2oBzTzP6Vf3j6xQKxVnJvHf9sYzy',
    NOW(),
    NOW()
)
ON CONFLICT (user_id) DO NOTHING;

-- 3) Link user to ADMIN role via join table user_role
INSERT INTO user_role (user_id, role_id) VALUES (1, 1)
ON CONFLICT DO NOTHING;

-- 4) Medicines (active = true)
INSERT INTO medicine (medicine_id, medicine_name, generic_name, manufacturer, dosage_form, strength, description, side_effects, contraindications, active)
VALUES
    (1, 'Aspirin', 'Acetylsalicylic Acid', 'Bayer', 'Tablet', '500mg', 'Pain reliever and anti-inflammatory', 'Stomach upset, bleeding', 'Ulcer, bleeding disorders', TRUE),
    (2, 'Ibuprofen', 'Ibuprofen', 'Advil', 'Tablet', '200mg', 'NSAID for pain and inflammation', 'Nausea, dizziness', 'Ulcer, kidney disease', TRUE),
    (3, 'Amoxicillin', 'Amoxicillin', 'Pfizer', 'Capsule', '500mg', 'Antibiotic', 'Rash, diarrhea', 'Penicillin allergy', TRUE)
ON CONFLICT (medicine_id) DO NOTHING;

COMMIT;

